### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/plain

### ISSUE THREAD

**Issue by UltraHylia** [KinTamashii/PythonTextObfuscator#1]
I'm not sure what's causing this, as the last time I tried this release, this issue was not present. If it's accessing content server-side, then it might be that the server has had a config change resulting in it returning a different mimetype?

I get the error message below consistently in the console, with %2E being added to the end of the URL each time. It does seem like some translation does happen; in this case, I inputted "Test", and the URL ended with "Hlola".

`https://translate.alefvanoon.xyz/api/v1/zu/mi/Hlola%2E 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://translate.alefvanoon.xyz/api/v1/zu/mi/Hlola')`

From what I've gathered looking online, the issue lies in either line 13, line 469, or both.

`return (await response.json())['translation'].replace('/','⁄')`

`text = (await response.json())['translation'].replace('/','⁄')`

Some of the solutions online referred to adding "content_type=None" or "content_type='text/plain'" into the brackets after "json", but this only seemed to cause further issues for me.

**Comment by KinTamashii** [comment]
<img width="1167" alt="Screen Shot 2022-02-11 at 8 14 32 PM" src="https://user-images.githubusercontent.com/77307334/153690321-e0540421-aaea-4748-9d92-529804c84bcd.png">
Remove "translate.alefvanoon.xyz" from LINGVA websites in config.py,

<img width="1420" alt="Screen Shot 2022-02-11 at 8 15 25 PM" src="https://user-images.githubusercontent.com/77307334/153690362-8a8f6580-d36e-4b9a-bc87-540411bf5713.png">
As you can see this implementation of lingva translate has been taken down by the service provider, which I am assuming is due a missed payment. The other two sites should work as expected.
